library_flask/books/routes.py
from flask import Blueprint, render_template, request, session, flash, jsonify
from library_flask import db
from library_flask.models import Member, Book, Transaction
from flask_login import login_required, current_user
from datetime import datetime
from library_flask.utils import get_user, get_members, get_books, get_transaction
import requests
today = datetime.now().date()

books = Blueprint('books', __name__)

@books.route('/books', methods=["GET", "POST"])
@login_required
def display_books():
    user = get_user()
    books = user.books_added
    return render_template('books.html', books=books)

@books.route('/import_books', methods=["GET", "POST"])
@login_required
def import_books():
    if request.args:
        args = request.args
        title, authors, publisher = args.get('title'), args.get('authors'), args.get('publisher')
        url = "https://frappe.io/api/method/frappe-library?"
        parameters = ''
        if title:
            parameters += f"title={title}&"
        if authors:
            parameters += f"authors={authors}&"
        if publisher:
            parameters += f"publisher={publisher}"

        try:
            response = requests.get(url + parameters)
            response.raise_for_status()  # Raise exception for HTTP errors
            data = response.json()
            if data.get('message'):
                session['books'] = data['message']
                return render_template('import-books.html', books=data['message'], title=title, authors=authors, publisher=publisher)
            else:
                return render_template('import-books.html', title=title, authors=authors, publisher=publisher, no_books='True')
        
        except requests.exceptions.RequestException as e:
            print("Error:", e)
            flash('An error occurred while trying to import books', 'error')
            return render_template('import-books.html')

    if request.method == "POST":
        data = request.form
        books = session.get('books')
        selected_books = data.getlist('books')
        filtered_books = [book for book in books if book['bookID'] in selected_books]
        for book in filtered_books:
            filter_criteria = {'book_id': book['bookID'], 'user_id': current_user.id}
            existing = Book.query.filter_by(**filter_criteria).first() 
            if not existing:
                new_book = Book(
                    title= book['title'],
                    authors= book['authors'],
                    publisher = book['publisher'],
                    rating= book['average_rating'],
                    isbn= book['isbn'],
                    book_id = book['bookID'],
                    user_id=current_user.id
                )
                db.session.add(new_book)
        db.session.commit() 
        flash('Book(s) imported successfully', 'success')
    return render_template('import-books.html')

@books.route('/book-issue', methods=['GET', 'POST'])
@login_required
def issue_books():
    if request.method == 'GET':
        members_filter_criteria = [
            Member.user_id == current_user.id,
            Member .amount_outstanding < 500
        ]
        books_filter_criteria = {'user_id': current_user.id, 'booked': False}
        members = get_members(members_filter_criteria)
        books = get_books(books_filter_criteria)
        return render_template('book-issue.html', members=members, books=books)

    data = request.form
    book = Book.query.get(data['book'])
    member = Member.query.get(data['member'])

    
    # update book record
    if book and member: 
        if member.amount_outstanding<500 and book not in member.books:
            book.booked = True
            book.member_id = data['member']
            #  record transaction
            transaction = Transaction(
                member_email = member.email,
                description = f'Book issued to member - {today}',
                book = data['book'],
                book_title = book.title,
                member_id = data['member'],
                booked_date = data['issue'],  
                monthly_amount = data['monthly_amount'],
                user_id = current_user.id,
            )
            db.session.add(transaction)
            db.session.commit()
            flash('Book issued successfully!', 'success')
        else:
            flash('Could not issue book', 'error')
    return render_template('book-issue.html')

@books.route('/book-return', methods=['GET', 'POST'])
@login_required
def return_book():
    if request.method == 'GET':
        members_filter_criteria = [ Member.user_id == current_user.id ]
        members = get_members(members_filter_criteria)
        return render_template('book-return.html', members=members)
    data = request.form
    filter_criteria = {'user_id': current_user.id, 'member_id': data['member'], 'book': data['book'] }
    transaction = get_transaction(filter_criteria)
    book = Book.query.get(data['book'])
    member = Member.query.get(data['member'])
    try:
        if book:
            book.booked = False
            book.member_id = None
            member.amount_outstanding = data['outstanding_amount']
        if transaction:
            transaction.return_date = data['return']
            transaction.total_amount= data['total_amount'] or 0
            transaction.received_amount= data['received_amount'] or 0
            transaction.description = f'{transaction.description} \n Book returned by member - {today}'
        db.session.commit()
        flash('Book returned to library', 'success')
    except:
        flash('Error recording book return', 'error')

    return render_template('book-return.html', message='Book returned by members')

@books.route('/get-issue-details', methods=["GET", "POST"])
@login_required
def get_issue_details():
    args = request.args
    member_id = args.get('member_id')
    if args.get('book_id'):
        filter_criteria = {'member_id': member_id, 'book': args.get('book_id')}
        transaction = get_transaction(filter_criteria)
        return jsonify({'result': transaction.booked_date, 'amount': transaction.monthly_amount})

    member = Member.query.get(member_id)
    books = [{'id': book.id, 'title': book.title} for book in member.books]
    return jsonify({'books': books})

library_flask/members/routes.py
from flask import Blueprint, redirect, render_template, request, url_for, flash
from library_flask import db
from library_flask.models import Member
from flask_login import login_required, current_user
from library_flask.utils import get_user, get_transactions, is_admin

members = Blueprint('members', __name__)

@members.route("/add_member", methods=["GET", "POST"])
@login_required
def add_member():
    if request.method == "GET":
        return render_template('add-member.html')
    data = request.form  
    filter_criteria = {'email': data['userEmail'], 'username': data['userName']}
    exisitng_member = Member.query.filter_by(**filter_criteria).first()
    if(exisitng_member):
        flash('A member with the same email or username already exists.')
        return redirect(url_for("members.add_member"))
    new_member = Member(
        fullname=data['userFullName'],
        username=data['userName'],
        email=data['userEmail'],
        user_id=current_user.id
    )
    db.session.add(new_member)
    db.session.commit()

    flash(f'New library member {data["userFullName"]} added', 'success')
    return render_template('add-member.html')

@members.route('/members/')
@login_required
def display_members():
    user = get_user()
    members = user.members_added
    return render_template('members.html', members=members)

@members.route('/members/<int:memberID>')
@login_required
def get_member(memberID):
    member = Member.query.get(memberID)
    if is_admin(member.user_id):
        # filter_criteria = {'user_id': current_user.id, 'member': memberID}
        # transactions = get_transactions(filter_criteria) or None
        transactions = member.member_transactions or None
        return render_template('member.html', member = member, transactions=transactions)
    else:
        return 'You are not authorized to access this page'

@members.route('/members/<int:memberID>/edit', methods=["GET", "POST"])
@login_required
def edit_member(memberID):
    member = Member.query.get(memberID)
    if is_admin(member.user_id):
        if request.method == "POST":
            data=request.form
            member.fullname = data['fullname']
            member.amount_outstanding = data['outstanding_amount']
            db.session.commit()
            flash('Member details updated','success')
            return redirect(f'/members/{member.id}')
        return render_template('edit-member.html', member = member)
    else:
        return 'You are not authorized to access this page'

library_flask/transactions/routes.py
from flask import Blueprint, redirect, render_template, request
from library_flask.models import Member, Transaction
from flask_login import login_required
from library_flask.utils import get_user, is_admin

transactions = Blueprint('transactions', __name__)

@transactions.route('/transactions')
@login_required
def display_transactions():
    user = get_user()
    transactions = user.transactions
    return render_template('transactions.html', transactions=transactions)

@transactions.route('/transactions/<int:transactionID>')
@login_required
def view_transaction(transactionID):     
    transaction = Transaction.query.get(transactionID)
    if is_admin(transaction.user_id):
        member = Member.query.get(transaction.member_id)
        return render_template('transaction.html', transaction = transaction, member=member)
    else:
        return 'You are not authorized to access this page'

library_flask/templates/add-member.html
{% extends "page.html" %}

{% block  content %}
<section class="text-gray-600 body-font relative px-4 md:px-0">
    <form class="lg:w-1/3 md:w-1/2 bg-white flex flex-col mx-auto w-full md:py-8 mt-8 md:mt-0" 
      action="/add_member" method="post"
      >

        <h2 class="text-gray-900 text-lg mb-1 font-medium title-font">Library Member Form</h2>
        <p class="leading-relaxed mb-5 text-gray-600"></p>
        
        <div class="relative mb-4">
          <label for="userFullName" class="leading-7 text-sm text-gray-600">Full Name</label>
          <input type="text" id="userFullName" name="userFullName" required class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
        </div>
        <div class="relative mb-4">
            <label for="userName" class="leading-7 text-sm text-gray-600">Username</label>
            <input type="text" id="userName" name="userName" required class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">

          </div>
        <div class="relative mb-4">
          <label for="email" class="leading-7 text-sm text-gray-600">Email</label>
          <input type="email" id="email" name="userEmail" required class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
        </div>
       
        <button type="submit" class="text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Submit</button>
      </div>
    </form>
  </section>
{% endblock %}

library_flask/templates/book-issue.html
{% extends "page.html" %}

{% block  content %}
<section class="text-gray-600 body-font relative px-4 md:px-0">
  <form class=" md:w-1/2 bg-white flex flex-col mx-auto w-full md:py-8 mt-8 md:mt-0" 
    action="/book-issue" method="post"
    >

      <h2 class="text-gray-900 text-lg mb-1 font-medium title-font">Book Issue</h2>

      <p class="leading-relaxed mb-5 text-gray-600"></p>
      <div class="relative mb-4">
        <label for="member" class="leading-7 text-sm text-gray-600">Member</label>
        <span class="text-sm text-gray-400">Filter Applied: Outstanding amout < Rs.500</span>
        <select id="member" name="member" class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
          {% if members %} 
          {% for member in members %}
          <option value="{{member.id}}">{{member.fullname}} - {{member.email}}</span></option>
          {% endfor %}
          {% endif %}
        </select>
      </div>
      <div class="relative mb-4">
        <label for="book" class="leading-7 text-sm text-gray-600">Book</label>
        <span class="text-sm text-gray-400">Filter Applied: Status not booked</span>
        <select id="book" name="book" class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
          {% if books %} 
          {% for book in books %}
          <option value="{{book.id}}">{{book.title}}</span></option>
          {% endfor %}
          {% endif %}
        </select>
      </div>

      <div class="relative mb-4 flex">
        <div class="w-1/2 mr-3">
        <label for="issue" class="leading-7 text-sm text-gray-600">Issue Date</label>
        <input type="date" id="issue" default="{{today}}" required name="issue" class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
        </div>
        <div class="w-1/2">
        <label for="monthly_amount" class="leading-7 text-sm text-gray-600">Monthly Fee</label>
        <input type="number" id="monthly_amount" name="monthly_amount" value="50" class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
        </div>
      </div>
     
      <button type="submit" class="text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Submit</button>
    </div>
  </form>
</section>
{% endblock %}

library_flask/templates/book-return.html
{% extends "page.html" %}

{% block  content %}
<section class="text-gray-600 body-font relative px-4 md:px-0">
  <form class=" md:w-1/2 bg-white flex flex-col mx-auto w-full md:py-8 mt-8 md:mt-0" 
    action="/book-return" method="post"
    >

      <h2 class="text-gray-900 text-lg mb-1 font-medium title-font">Book Return</h2>
      <p class="leading-relaxed mb-5 text-gray-600"></p>
      <div class="relative mb-4">
        <label for="member" class="leading-7 text-sm text-gray-600">Member</label>
        <select id="member" name="member" required class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
          <option value="">Select Member</span></option>
          {% if members %} 
          {% for member in members %}
          <option value="{{member.id}}">{{member.fullname}} - {{member.email}}</span></option>
          {% endfor %}
          {% endif %}
        </select>
      </div>
      <div class="relative mb-4">
        <label for="book" class="leading-7 text-sm text-gray-600">Book</label>
        <select id="book" name="book" required class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
          <option value="">Choose Book</span></option>
          <!-- {% if books %} 
          {% for book in books %}
          <option value="">Choose Book</span></option>
          {% endfor %}
          {% endif %} -->
        </select>
      </div>

      <div class="relative mb-4 flex">
        <div class="w-1/2 mr-3">
          <label for="issue" class="leading-7 text-sm text-gray-600">Issue Date</label>
        <input type="date" id="issue" required default="{{today}}" required name="issue" class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
        </div>
        <div class="w-1/2">
          <label for="return" class="leading-7 text-sm text-gray-600">Return Date</label>
        <input type="date" id="return" required name="return" class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
        </div>
      </div>

      <div class="relative mb-4 flex">
        <div class="w-1/2 mr-3">
          <label for="monthly_amount" class="leading-7 text-sm text-gray-600">Monthly Fee</label>
          <input type="number" disabled id="monthly_amount" name="monthly_amount" class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">

          <label for="received_amount" class="leading-7 text-sm text-gray-600">Amount Received</label>
          <input type="number" id="received_amount" name="received_amount" class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
          <span class="text-sm text-gray-400">Total amount received from member</span>
        </div>
        <div class="w-1/2 mt-3">
          <label for="total_amount" value='0' class="leading-7 text-sm text-gray-600">Total Fee</label>
          <input type="number" id="total_amount" name="total_amount" class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">

          <label for="outstanding_amount" class="leading-7 text-sm text-gray-600">Outstanding Amount</label>
          <input type="number" id="outstanding_amount" name="outstanding_amount" class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
        </div>
      </div>
     
      <button type="submit" class="text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Submit</button>
    </div>
  </form>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function() {
        // filter book field based on chosen member to dispaly only issued books
        $('#member').change(function() {
            let memberId = $(this).val();
            if (!memberId){
                return ''
            }
            $.ajax({
                type: 'GET',
                url: '/get-issue-details',  // URL to fetch books associated with the selected member
                data: {member_id: memberId},
                success: function(response) {
                    $('#book').empty(); // Clear existing options
                    console.log(response)
                    if (response.books) {
                        $('#book').append('<option value="">Choose Book</option>')
                        $.each(response.books, function(index, book) {
                            $('#book').append('<option value="' + book.id + '">' + book.title + '</option>');
                        });
                    }
                },
                error: function(xhr, status, error) {
                    console.error(xhr.responseText, status, error);
                }
            });
        });

        // fetch and display issue date and monthyl amount
        $('#book').change(function() {
            let memberId = $('#member').val();
            let bookId = $('#book').val();
            if (!memberId || !bookId){
                return ''
            }
            $.ajax({
                type: 'GET',
                url: '/get-issue-details',
                data: {member_id: memberId, book_id: bookId},
                success: (response) => {
                    let date = new Date(response.result), 
                        year = date.getFullYear(),
                        month = (date.getMonth() + 1).toString().padStart(2, '0'),
                        day = date.getDate().toString().padStart(2, '0');
                    let formattedDate = `${year}-${month}-${day}`;
                    $('#issue').val(formattedDate);
                    $('#monthly_amount').val(response.amount);
                    
                },
                error: function(xhr, status, error) {
                    console.error(xhr.responseText, status, error);
                }
            });
        });
    
        $('#return').change(()=>{
            let issue = new Date($('#issue').val()),
                return_date = new Date($('#return').val())
            let daysDifference = Math.round( (return_date - issue) / (1000 * 60 * 60 * 24))
            let monthly = $('#monthly_amount').val()
            $('#total_amount').val(Math.trunc(daysDifference / 30) * monthly);
            // console.log(daysDifference); // Output the difference in days
        })

        $('#received_amount').change(()=>{
          let total = $('#total_amount').val(),
              received = $('#received_amount').val()
          if (total > received ){
            $('#outstanding_amount').val(total - received)
          }
        })

        })
    
</script>

</section>
{% endblock %}

library_flask/templates/books.html
{% extends "page.html" %}
{% block content %}

<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-col w-full mb-20">
        <h1 class="text-3xl font-medium title-font mb-4 text-gray-900">Library Books</h1>
        {% if books %} 
        <div class=" w-full mx-auto overflow-auto">
          <table class="table-auto w-full text-left whitespace-no-wrap">
            <thead>
              <tr>
                <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Title</th>
                <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Author(s)</th>
                <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Publisher</th>
                <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Rating</th>
                <th class="w-10 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tr rounded-br">Status</th>
              </tr>
            </thead>
            <tbody>
              {% for book in books %}
              <tr>
                <td class="px-4 py-3 w-1/3">{{book.title}}</td>
                <td class="px-4 py-3 w-1/3">{{book.authors}}</td>
                <td class="px-4 py-3">{{book.publisher}}</td>
                <td class="px-4 py-3">{{book.rating}}</td>
                <td class="px-4 py-3">
                  {{'Booked' if book.booked else ''}}
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>

        {% else %}
        <p class="lg:w-2/3 leading-relaxed text-base">List of imported books are displayed here</p>
        {% endif %}
      </div>
      
      <div class="flex mt-4 lg:w-2/3 w-full mx-auto">
        <button class="flex mx-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
          <a href="/import_books">Add Books</a>
        </button>
      </div>
    </div>
</section>

{% endblock %}

library_flask/templates/error.html
<!-- {% extends "page.html" %}
{% block content %}

{% if %}

{% endblock %} -->

library_flask/templates/home.html
{% extends "page.html" %}

{% block  content %}

<section class="text-gray-600 body-font">
  <div class="container px-5 md:py-24 mx-auto">

    <div class="flex flex-col w-full md:mb-20">
      <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">Library Manager</h1>
    </div>
    <div class="md:flex"> 
      <div class="md:border-r md:w-3/5 md:pr-12">
        <div class="flex flex-wrap md:mb-4 -m-4 text-center">
          <div class="p-4 md:w-1/2 w-full">
            <a href="{{url_for('books.import_books')}}" class="cursor-pointer block border-2 border-gray-200 px-4 py-6 rounded-lg">
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="text-indigo-500 w-12 h-12 mb-3 inline-block" viewBox="0 0 24 24">
                <path d="M8 17l4 4 4-4m-4-5v9"></path>
                <path d="M20.88 18.09A5 5 0 0018 9h-1.26A8 8 0 103 16.29"></path>
              </svg>
              <h3 class="title-font font-medium text-2xl text-gray-900">Import Books</h3>
              <p class="leading-relaxed">Search and Import Books</p>
            </a>
          </div>
          <div class="p-4 md:w-1/2 w-full">
            <a href="{{url_for('members.add_member')}}" class="cursor-pointer block border-2 border-gray-200 px-4 py-6 rounded-lg">
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="text-indigo-500 w-12 h-12 mb-3 inline-block" viewBox="0 0 24 24">
                <path d="M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2"></path>
                <circle cx="9" cy="7" r="4"></circle>
                <path d="M23 21v-2a4 4 0 00-3-3.87m-4-12a4 4 0 010 7.75"></path>
              </svg>
              <h3 class="title-font font-medium text-2xl text-gray-900">Add Member</h3>
              <p class="leading-relaxed">Add New Members</p>
            </a>
          </div> 
        </div>
        <div class="flex flex-wrap -m-4 text-center">
          <div class="p-4 md:w-1/2 w-full">
            <a href="{{url_for('books.issue_books')}}" class="cursor-pointer block border-2 border-gray-200 px-4 py-6 rounded-lg">
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="text-indigo-500 w-12 h-12 mb-3 inline-block" viewBox="0 0 24 24">
                <path d="M3 18v-6a9 9 0 0118 0v6"></path>
                <path d="M21 19a2 2 0 01-2 2h-1a2 2 0 01-2-2v-3a2 2 0 012-2h3zM3 19a2 2 0 002 2h1a2 2 0 002-2v-3a2 2 0 00-2-2H3z"></path>
              </svg>
              <h3 class="title-font font-medium text-2xl text-gray-900">Issue Book</h3>
              <p class="leading-relaxed">Issue Book to Members</p>
            </a>
          </div>
          <div class="p-4 md:w-1/2 w-full">
            <a href="{{url_for('books.return_book')}}" class="cursor-pointer block border-2 border-gray-200 px-4 py-6 rounded-lg">
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="text-indigo-500 w-12 h-12 mb-3 inline-block" viewBox="0 0 24 24">
                <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path>
              </svg>
              <h3 class="title-font font-medium text-2xl text-gray-900">Book Return</h3>
              <p class="leading-relaxed">Record Book Returns</p>
            </a>
          </div>
        </div>
      </div>

      <div class="md:w-1/5 md:pl-12 my-4 md:my-0 text-center md:text-left">

        <h2 class="title-font inline font-semibold text-gray-800 tracking-wider text-md mb-3">LINKS</h2>
        <nav class="flex flex-col list-none md:mt-4 -mb-1">
          <a class="text-gray-600 hover:text-gray-800 i" href="{{url_for('books.display_books')}}">Books</a>
          <a class="text-gray-600 hover:text-gray-800" href="{{url_for('members.display_members')}}">Members</a>
          <a class="text-gray-600 hover:text-gray-800" href="{{url_for('transactions.display_transactions')}}">Transactions</a>
        </nav>

      </div>
    </div>
  </div>
</section>
{% endblock %}

library_flask/templates/login.html
{% extends "page.html" %}

{% block  content %}
<section class="text-gray-600 body-font relative px-4 md:px-0">
    <form class="lg:w-1/3 md:w-1/2 bg-white flex flex-col mx-auto w-full md:py-8 mt-8 md:mt-0" 
      action="/login" method="post"
      >

        <h2 class="text-gray-900 text-lg mb-1 font-medium title-font">Login As Administrator</h2>
        <div class="relative mb-4">
          <label for="email" class="leading-7 text-sm text-gray-600">Email</label>
          <input type="email" id="email" name="userEmail" class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
        </div>
        <div class="relative mb-4">
          <label for="password" class="leading-7 text-sm text-gray-600">Password</label>
          <input type="password" id="password" name="userPassword" class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
        </div>
       
        <button type="submit" class="text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Login</button>
      </div>
    </form>
  </section>
{% endblock %}